### ISSUE TITLE
Rework Tracking Issue: Package currently not working

### ISSUE THREAD

**Issue by josh-hemphill** [josh-hemphill/vite-plugin-favicon#7]
Current TODOs:

  - [ ] #2
  - [ ] Update config files' file paths from the file IDs that Vite generates #1
  - [ ] Finish new image generation library [josh-hemphill/favigen](https://github.com/josh-hemphill/favigen) that can handle file name updates
  - [ ] Improve documentation by not listing no-op options, just say it accepts webpack favicon config #6 
  - [ ] Add output path overrides

**Comment by brunodmn** [comment]
Sry, is the plugin working?
I've just tried, when I build the app, it generates the icons, but with wrong href on dist/index.html

**Comment by josh-hemphill** [comment]
Kind of, the html/paths being wrong is a result of the favicons library not exposing any functionality to change or track that part of it.
I haven't touched this in a while, but I'm planning to return to it in the next month or so; I'm going to have to write a separate favicon library, because `favicons` is really not meant to be used as library even though that's what it's most often used for.

**Comment by brunodmn** [comment]
Got it, thank you for answering.

**Comment by demc** [comment]
> * [ ]  Finish new image generation library [josh-hemphill/favigen](https://github.com/josh-hemphill/favigen) that can handle file name updates
> *

Any updates? It appears this library is broken (i.e. the href attributes are wrong upon injection).
